### ISSUE TITLE
Kurzweil K2000 "not a DOS disk"

### ISSUE THREAD

**Issue by Rose62035** [ZuluSCSI/ZuluSCSI-firmware#382]
I believe there's a problem with the ZuluSCSI RP2040 Rev2023a firmware, with a Kurzweil K2000 with OS 3.87J.
The ZuluSCSI board works fine with a Kurzweil K2500 and K2600, but not the K2000. I updated the firmware to the latest, 2/6/2024, didn't help.
Do I need to post the Zululog, to figure out the issue?

**Comment by aperezbios** [comment]
@Rose62035 yes, we're going to need a _debug-enabled_ zululog in order to have a good chance of being able to understand what's going on. Hard data is necessary. With the ZuluSCSI off, please switch the debug DIP switch on, and then power on the problem machine, and attempt to use it as normal. Then, upload the resulting zululog here.

**Comment by chickeneps** [comment]
"Not a DOS disk" refers to the media the K2000 is reading. You didn't mention anything about what image file you are using, or if you are using a image at all. Please clarify.

**Comment by chickeneps** [comment]
I just tested it on our K2000 with v3.87, used a single 2GB file named HD2.img and the K2000 saw the ID on 2 and I formatted it and then saved a NEWFILE.KRZ then loaded it in. Worked fine.

**Comment by aperezbios** [comment]
Since this does not appear to be an issue with the ZuluSCSI itself, I'm closing this issue, since it's non-actionable.
